### ISSUE TITLE
[Discuss] Wiki Integration

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#15]
We might want to have a built in or in some way integrated wiki as a knowledge base for members to reference and also to easily see who knows about the topic so that they can contact them.

From a technical standpoint a simple wiki would be easy to add. But more advanced features might warrant using an external solution.

**Comment by rushsteve1** [comment]
Technical ideas for a built-in RCOS wiki:
- Organized by topic and tags
- Sidebar of contributors to page
- Saved in database as Diffs to allow versioning
- Two database tables:
    - `pages`: the pages their tags and whatnot 
    - `revisions`: the revisions to pages and who they were by
- Markdown support is already in

**Comment by rushsteve1** [comment]
For an external wiki here is a list of possible software solutions:
https://github.com/Kickball/awesome-selfhosted#wikis

**Comment by joshlebed** [comment]
On a non-technical note - how should we incentivize experienced and senior members of the RCOS community to contribute to the wiki? Contributions for the semester could be factored into grading, for example.

**Comment by rushsteve1** [comment]
@joshlebed Perhaps factor it into part of the status reports? If you're taking time to learn something write it down for others I guess.

**Comment by rushsteve1** [comment]
Features necessary for any Wiki software we use:
- Obviously must be FOSS and self-hostable
- If an external database is required it must support Postgres
- Read/Write Permission controls
- Revision history
- Hierarchical navigation


Currently here are what I currently consider the best options:
- DokuWiki
    - **Pros:** No database required, many plugins
    - **Cons:** Ugly by default, a bit clunky to use at times, no markdown support
- WikiJS 2
    - **Pros:** Lots of features, supports markdown
    - **Cons:** Unfinished beta, Javascript heavy, slightly annoying UX.
- Bookstack
    - **Pros:** Nice looking, supports markdown
    - **Cons:** "book/shelf" model is confusing

Of these three I think **DokuWiki** would be the best choice for now, and likely the easiest to migrate *away* from if we change our mind.
However, depending on the development status of WikiJS 2 I would chose that instead.

**Comment by rushsteve1** [comment]
We went with Dokuwiki. Not sure why this is still open actually.
