### ISSUE TITLE
External Projects

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#21]
Having a method to list external projects on the website and show people who have worked on them and scrape their commits would be useful and help promote contribution to larger projects.

This should be a simple matter of adding a toggle to a project marking it as "external"

**Comment by jkuruzovich** [comment]
Severino Center would be interested in a general project visibility application like rcos.io to increase the visibility of the innovation ecosystem at rensselaer in general. This could play a role like https://startuptree.co in tracking startups.

**Comment by rushsteve1** [comment]
This was completed by #68
