### ISSUE TITLE
Unique Emails

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#22]
**Describe the bug**
If you try to sign up with an email that is already taken it causes an error and crashes the server.

Related to #5 

**To Reproduce**
1. Go to 'Sign Up'
2. Try to sign up with an email that there is already an account for
3. Page errors and server crashes

**Expected behavior**
Prompts the user with an error and doesn't crash the server

**Comment by rushsteve1** [comment]
@BrianMejia The commits related to #5 should provide a good example on how this should be handled.

**Comment by BrianMejia** [comment]
Thanks! Was looking for an example for a while, will get on it.

**Comment by rushsteve1** [comment]
Closed by #23
