### ISSUE TITLE
Add Same User to group

### ISSUE THREAD

**Issue by 4very** [rcos/observatory-new#24]
**Describe the bug**
You can add the same user multiple times to the same project.

**To Reproduce**
1. Create a new project
2. Go to project page
3. Click add user
4. Select a user already in the group from the drop down menu
5. Click Add

**Expected behavior**
The member should not show up on the drop down menu whenever you want to add a new user to the group.

**Comment by rushsteve1** [comment]
Somewhat related to #5

**Comment by JadeWang96** [comment]
The project owner is unable to delete the project or this permission is only for admin?

**Comment by rushsteve1** [comment]
For now only admins can delete projects. We like having a record of all projects anyone at RCOS has ever worked on so we don't want people deleting them.
