### ISSUE TITLE
Add user when there are no eligible users

### ISSUE THREAD

**Issue by 4very** [rcos/observatory-new#25]
**Describe the bug**
You get a 422 error if you try to add a user to a group where there are no users eligible to be added.

**To Reproduce**
1. Go to "Groups"
2. Add all current users via the "Add User" button
3. When all users are in the group click "Add User" again
4. The drop down list should be empty, click "Add"
5. See error

**Expected behavior**
The "add button" user should be grayed out if there are no eligible members to be added to the group.

**Screenshots**
https://i.imgur.com/bnRc9Uu.png

**Comment by rushsteve1** [comment]
I believe this issue has been fixed in practice by @BrianMejia so I am going to close this issue.
