### ISSUE TITLE
No collision detection for git usernames

### ISSUE THREAD

**Issue by 4very** [rcos/observatory-new#27]
**Describe the bug**
Whenever you try to sign up with a github handle that is already in the database, the website will crash.

**To Reproduce**
1. Go to sign up
2. Fill in with the github handle that is already in the database
3. Profit

**Expected behavior**
There should be a pop up that says "Error: That github handle is already in use".

**Comment by TungE** [comment]
Trying to sign up with an existing email address has the same effect

**Comment by rushsteve1** [comment]
This should be a similar fix to #23

**Comment by rushsteve1** [comment]
Closed by #47
