### ISSUE TITLE
Redirect attendance to Dashboard

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#30]
Submitting a valid attendance code redirects you to main page, should probably redirect to dashboard so users can view the attendance recently submitted.

**Comment by rushsteve1** [comment]
This is a very easy first issue for anyone and should be as simple as changing this line
https://github.com/rcos/observatory-new/blob/a341f14e63cbd4d94ede1fdfb8d20b01d4345aeb/src/attend/handlers.rs#L58
