### ISSUE TITLE
Members able to view group meeting codes

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#32]
**Describe the bug**
Members can access mentor/admin group control panel through dashboard link.

**To Reproduce**
1. Create new member
2. Go to dashboard
3. Large group link is clickable and directs to mentor/admin group page, which includes past attendance meeting codes

**Expected behavior**
Should either be prevented from viewing group pages entirely or shown less information

**Comment by rushsteve1** [comment]
This should be a good first issue since you should just have to add a guard to here:
https://github.com/rcos/observatory-new/blob/a341f14e63cbd4d94ede1fdfb8d20b01d4345aeb/templates/group/group.html#L63
There are examples of guards in that file a bit higher up than where I linked.

**Comment by 4very** [comment]
cannot reproduce due to issue #28
