### ISSUE TITLE
Members can log attendance from groups they are not in

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#33]
**Describe the bug**
Able to log attendance using a code that was not generated for a group which that member is part of.

**To Reproduce**
1. Create new group and generate attendance code
2. Create new member
3. Attempt to log new group's attendance with new member without adding member to group

**Expected behavior**
Should give error message similar to the invalid code error, stating that user is not in that code's group.

**Comment by rushsteve1** [comment]
This leads into #34 but the direct issue has been completed so I'm closing this.
