### ISSUE TITLE
Submitting same attendance code

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#34]
**Describe the bug**
Members can submit the same attendance code multiple times.  
Pictured is attendance of a user who has submitted a large group attendance code 4 times, a different large group attendance code 2 times, and a small group attendance that they are not part of 1 time.  
EDIT: counting of total attendances which are possible for the student to have gone to is CORRECT, only issue with allowing attendances to be logged which they shouldn't be able to submit
![image](https://user-images.githubusercontent.com/35616181/59067813-8af4c800-8880-11e9-90fe-ec35d2eeed58.png)

**Expected behavior**
Should get error message stating that attendance code was already submitted.

**Comment by rushsteve1** [comment]
Closed by #45
