### ISSUE TITLE
New Project button directs to a current project (Chrome)

### ISSUE THREAD

**Issue by JadeWang96** [rcos/observatory-new#36]
**Describe the bug**
After joining in an existing project, click the New Project button will direct to the existing project.

**To Reproduce**
1. Go to an existing project and click join
2. After successfully joining, return to Projects page
3. Click New Project

**Expected behavior**
Direct to the page creating a new project

**Desktop (please complete the following information):**
 - OS: [Window 10 Pro]
 - Browser [Chrome] This problem does not appear on Firefox
 - Version [73.0.3683.103 (Official Build) (64-bit)]

**Additional context**

**Comment by sommea** [comment]
same as #31

**Comment by 4very** [comment]
Oops i didnt mean to do that, but this is the same as #31

**Comment by JadeWang96** [comment]
Oops, sorry for the duplicate. Another problem for Chrome is unable to use USER SEARCH and it directs to a certain user file page.
