### ISSUE TITLE
Audit Logging

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#64]
When certain actions are taken we should log to some kind of audit log so that we can check it and make sure no bad actors are happening.

**Describe the solution you'd like**
Log important events to a log file or a table in the database.

**Comment by BrianMejia** [comment]
Adding a function to `main.rs` seems to be a portable solution. We can have a function that takes in an optional file name that the log could be written to.

Some suggestions for what should be audited:
Action
User ID committing the action
User Name associated with ID
Time (Uncertain of date format)

Any other suggestions/modifications are welcome.

**Comment by BrianMejia** [comment]
We are going to look into crates that do logging, the initial implementation could be complex but further use should be simplified.

@rushsteve1 and anyone else feel free to comment which actions should be logged.

**Comment by rushsteve1** [comment]
This was largely completed by #71 so I'll close this issue. More logging can be added whenever now.
