### ISSUE TITLE
[Discuss] Attendance Code Validation

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#7]
On the current https://rcos.io users have a random chance to need to be validated by a mentor. This is intended to stop people from putting in attendance codes when they are not there, but in reality I believe that it only serves to annoy mentors and coordinators and does little to stop people from skipping meetings.

That said I think we need a new system for making sure that people attend the meetings that they are supposed to and am asking for any ideas that you might have regarding it.

**Comment by OliviaLundelius** [comment]
Just an idea, perhaps a significantly shortened time period in which they can submit an attendance code.  My primary concern is people showing up at the end of large group to submit the attendance code and then leave.  We could have attendance be submit-able for a 10 minute period at some time during a meeting.

**Comment by rushsteve1** [comment]
That's not a bad idea. We would have to make sure to mix up when we give out the code but that's not too hard.

My concern is then people will simply text their friends the code who can just immediately put it in. But I guess geo-location is more Venue's area.

**Comment by rushsteve1** [comment]
After discussion we are just going forward with the existing model for attendance

#65 is the new tracking issue.
