### ISSUE TITLE
Delete Project is not deleting the project

### ISSUE THREAD

**Issue by DowdSean** [rcos/observatory-new#73]
When you click the the delete project button it says "are you sure". I click ok I am still on the project page and if I leave the individual project page and just go to the project list page the project is still there

**To Reproduce**
1. Done in chrome browser 
2. Created a new project ( tried again can't delete the first or second project I created)
3. Used a Github link for Repos for the first project and a youtube video url for the second both won't delete

It should when the project is deleted take you to the general project page that lists all the over projects on the website but it does not do that. And you stay on the individual project page after you press delete. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Smartphone 
Haven't tested it on smartphones

**Comment by rushsteve1** [comment]
This issue was tracked down to a permissions error on the `delete` HTTP handler.
