### ISSUE TITLE
User and dashboard pages fail to load after creating project.

### ISSUE THREAD

**Issue by bernep** [rcos/observatory-new#74]
**Describe the bug**
When creating a new project, or after you've been added to a new project, your user and dashboard fail to load.

**To Reproduce**
1. Go to 'Projects'
2. Click on 'New Project'
3. Create The Project
4. Now your user and dashboard pages are blank.

Also...
1. Add a user to your project.
2. Now you cannot see their user page, and their dashboard will fail to load.

**Expected behavior**
The user and dashboard should appear with the proper information.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox && Chrome
 - Version: Firefox 69.0.3 (64-bit) && Chrome 77.0.3865.120 (Official Build) (64-bit)

**Smartphone:**
Untested on smartphone.

**Additional Context**
This does not seem to affect users who created or were added to a project prior to a few weeks ago. Most users' pages still work just fine right now.

**Comment by bernep** [comment]
I kept shortening the title. Still new to this. Ignore basically all of these initial edits.

**Comment by bernep** [comment]
The issue does not seem to be caused by the .html template for the dashboard and user pages. We deleted everything on those templates and wrote some generic html code and the issue still persists.

**Comment by rushsteve1** [comment]
I tracked this issue all the way down to a bug in `project_commits` where if the repo specified is not *actually* a valid Git repository then it will return `None` which causes an error`.

**Comment by rushsteve1** [comment]
The issue was fixed by f71d9ac
