### ISSUE TITLE
Attendance Code not case sensitive

### ISSUE THREAD

**Issue by xtreme765** [rcos/observatory-new#75]
**Describe the bug**
When entering a correct attendance code in uppercase into the Attend bar the user is prompted that the attendance code is incorrect.

**To Reproduce**
1. Go to Attend
2. Enter a correct attendance code in uppercase into the box
3. Click submit

**Expected behavior**
Attendance is verified and user is redirected to Dashboard

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome
 - Version 77.0.3865.120

**Comment by rushsteve1** [comment]
Fixed by #77
