### ISSUE TITLE
String Input is not limited

### ISSUE THREAD

**Issue by xtreme765** [rcos/observatory-new#87]
**Describe the bug**
When inputting anything like usernames, Github handles, project names, emails, biographies, etc. there is no limit to how long the inputting String can be currently.

**To Reproduce**
1. Go to any editing page on the site.
2. Type in any length of characters (1000+ is good).
3. Submit/enter these changes.
4. Check the Dashboard/Users/Project pages and observe the chaos.

**Expected behavior**
Inputs should be limited on a case by case scenario so that no part of the site will be unnecessarily elongated or hard to read if someone abuses this power.

**Desktop (please complete the following information):**
- OS: Windows 10 Home
- Browser Chrome
- Version 77.0.3865.120

**Comment by rushsteve1** [comment]
Closed by #93
